databases:
  - name: tweetbox
    plan: free
    databaseName: tweetbox
    user: head

services:
  - type: web
    plan: free
    name: head
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn head.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgresql://tweetbox_user:w1XpaslLOtozLl5Q0keA4c0XvPKqkpEq@dpg-cto2su3qf0us73ale510-a/tweetbox
        fromDatabase:
          name: tweetbox
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4